### ISSUE TITLE
Race in dead-await detection / iced-runtime-3

### ISSUE THREAD

**Issue by maxtaco** [maxtaco/coffee-script#175]
Repro:

``` coffeescript
foo = (cb) -> cb()

bar = (cb) ->
  await
    foo defer()
    setTimeout defer(), 100
  console.log "done"
  await setTimeout defer(), 1000
  cb()

await bar defer()
```

Output:

```
ICED warning: Entered dead await at <anonymous> (undefined:8)
```

**Comment by maxtaco** [comment]
For whoever wants to take a crack at this, I think the right solution here is to initialize an `await` with a counter of 1 and then call fulfill when control hits the end of it.  I think this is what we had originally in iced2.

**Comment by zapu** [comment]
You are correct, I see where the issue is now. I solved this for a case when there is one async call that callbacks immediately, but I forgot that there can be more than one. (**EDIT**: disregard, my patch before was for a different issue.)

The other way would be to assign defers do temporary variables before any call, so in the end it would be doing something like:

```
await
   temp1 = defer()
   temp2 = defer()
   foo temp1
   setTimeout temp2, 100
```

**Comment by zapu** [comment]
I believe I have a fix. I'm doing more tests and preparing a pull request.

**Comment by zapu** [comment]
I also have another version of the fix (which was my initial try at this issue...) that checks if `await` block has more than one `defer()` call inside and only does the "counter=1" thing in such cases, by setting the counter manually and calling _fulfill manually. But the runtime change seems cleaner.
